nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['content-type', 'authorization']
        expose_headers: []
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['content-type', 'authorization']
            max_age: 3600
